services:
  - type: web
    name: barbershop
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd barbershop && gunicorn barbershop.wsgi:application"
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ""
      # Укажи свои значения в панели Render:
      # - key: DJANGO_SECRET_KEY
      #   value: "change-me"
      # - key: DATABASE_URL
      #   value: "postgres://..."
